creation_rules:
  - path_regex: secrets[\\/].*\.yaml$
    key_groups:
      - age:
          # Ihr persönlicher Schlüssel, damit Sie die Datei bearbeiten können
          - "age1v30cyk9yztwwkkaqyd2zfwv3vd5rcge5kykfm2x9q3kf99epdyfqlj2cxf"
          # Der öffentliche age-Schlüssel Ihres Hauptrechners
          - "age1c4gcs4uy9tnwk3uz370l3lhwv3lc3mgzt6up6qk64lfltnxg7ehs256njf"
          # Der öffentliche age-Schlüssel Ihres Laptops
          - "age1t2u3ht4340l7z3252cq4m7atx4mfx4lqsyqwmg5tvmsxrh5jcdrs8hh0mu"
